import { Phrase, Conversation } from "./types";

export const phrases: Phrase[] = [
  // --- CHÀO HỎI (GREETINGS) ---
  {
    id: 1,
    japanese: "おはようございます",
    romaji: "Ohayou gozaimasu",
    vietnamese: "Chào buổi sáng",
    category: "Chào hỏi",
  },
  {
    id: 2,
    japanese: "こんにちは",
    romaji: "Konnichiwa",
    vietnamese: "Xin chào (buổi trưa/chung)",
    category: "Chào hỏi",
  },
  {
    id: 3,
    japanese: "こんばんは",
    romaji: "Konbanwa",
    vietnamese: "Chào buổi tối",
    category: "Chào hỏi",
  },
  {
    id: 4,
    japanese: "おやすみなさい",
    romaji: "Oyasuminasai",
    vietnamese: "Chúc ngủ ngon",
    category: "Chào hỏi",
  },
  {
    id: 5,
    japanese: "さようなら",
    romaji: "Sayounara",
    vietnamese: "Tạm biệt",
    category: "Chào hỏi",
  },
  {
    id: 6,
    japanese: "ありがとうございます",
    romaji: "Arigatou gozaimasu",
    vietnamese: "Cảm ơn rất nhiều",
    category: "Chào hỏi",
  },
  {
    id: 7,
    japanese: "すみません",
    romaji: "Sumimasen",
    vietnamese: "Xin lỗi / Cho tôi hỏi (Excuse me)",
    category: "Chào hỏi",
  },
  {
    id: 8,
    japanese: "ごめんなさい",
    romaji: "Gomennasai",
    vietnamese: "Xin lỗi (khi làm sai)",
    category: "Chào hỏi",
  },
  {
    id: 9,
    japanese: "お元気ですか？",
    romaji: "Ogenki desu ka?",
    vietnamese: "Bạn có khỏe không?",
    category: "Chào hỏi",
  },
  {
    id: 10,
    japanese: "元気です",
    romaji: "Genki desu",
    vietnamese: "Tôi khỏe",
    category: "Chào hỏi",
  },
  {
    id: 11,
    japanese: "またね",
    romaji: "Mata ne",
    vietnamese: "Hẹn gặp lại nhé (thân mật)",
    category: "Chào hỏi",
  },
  {
    id: 12,
    japanese: "いってきます",
    romaji: "Ittekimasu",
    vietnamese: "Tôi đi đây (người đi nói)",
    category: "Chào hỏi",
  },
  {
    id: 13,
    japanese: "いってらっしゃい",
    romaji: "Itterasshai",
    vietnamese: "Bạn đi nhé (người ở nhà nói)",
    category: "Chào hỏi",
  },

  // --- GIỚI THIỆU (SELF INTRODUCTION) ---
  {
    id: 14,
    japanese: "はじめまして",
    romaji: "Hajimemashite",
    vietnamese: "Rất vui được gặp bạn (lần đầu)",
    category: "Giới thiệu",
  },
  {
    id: 15,
    japanese: "私はベトナム人です",
    romaji: "Watashi wa Betonamu-jin desu",
    vietnamese: "Tôi là người Việt Nam",
    category: "Giới thiệu",
  },
  {
    id: 16,
    japanese: "ベトナムから来ました",
    romaji: "Betonamu kara kimashita",
    vietnamese: "Tôi đến từ Việt Nam",
    category: "Giới thiệu",
  },
  {
    id: 17,
    japanese: "名前は何ですか？",
    romaji: "Namae wa nan desu ka?",
    vietnamese: "Tên bạn là gì?",
    category: "Giới thiệu",
  },
  {
    id: 18,
    japanese: "私の名前はAです",
    romaji: "Watashi no namae wa A desu",
    vietnamese: "Tên tôi là A",
    category: "Giới thiệu",
  },
  {
    id: 19,
    japanese: "よろしくお願いします",
    romaji: "Yoroshiku onegaishimasu",
    vietnamese: "Mong được giúp đỡ",
    category: "Giới thiệu",
  },
  {
    id: 20,
    japanese: "英語が話せますか？",
    romaji: "Eigo ga hanasemasu ka?",
    vietnamese: "Bạn có nói được tiếng Anh không?",
    category: "Giới thiệu",
  },
  {
    id: 21,
    japanese: "日本語が少ししか話せません",
    romaji: "Nihongo ga sukoshi shika hanasemasen",
    vietnamese: "Tôi chỉ nói được một chút tiếng Nhật",
    category: "Giới thiệu",
  },
  {
    id: 22,
    japanese: "わかりません",
    romaji: "Wakarimasen",
    vietnamese: "Tôi không hiểu",
    category: "Giới thiệu",
  },
  {
    id: 23,
    japanese: "もう一度お願いします",
    romaji: "Mou ichido onegaishimasu",
    vietnamese: "Làm ơn nhắc lại lần nữa",
    category: "Giới thiệu",
  },

  // --- GIAO TIẾP (GENERAL COMMUNICATION) ---
  {
    id: 1001,
    japanese: "はい",
    romaji: "Hai",
    vietnamese: "Vâng / Có",
    category: "Giao tiếp",
  },
  {
    id: 1002,
    japanese: "いいえ",
    romaji: "Iie",
    vietnamese: "Không",
    category: "Giao tiếp",
  },
  {
    id: 1003,
    japanese: "そうです",
    romaji: "Sou desu",
    vietnamese: "Đúng vậy",
    category: "Giao tiếp",
  },
  {
    id: 1004,
    japanese: "違います",
    romaji: "Chigaimasu",
    vietnamese: "Sai rồi / Không phải",
    category: "Giao tiếp",
  },
  {
    id: 1005,
    japanese: "もっとゆっくり話してください",
    romaji: "Motto yukkuri hanashite kudasai",
    vietnamese: "Làm ơn nói chậm hơn một chút",
    category: "Giao tiếp",
  },
  {
    id: 1006,
    japanese: "書いてください",
    romaji: "Kaite kudasai",
    vietnamese: "Làm ơn viết ra giúp tôi",
    category: "Giao tiếp",
  },
  {
    id: 1007,
    japanese: "大丈夫です",
    romaji: "Daijoubu desu",
    vietnamese: "Không sao đâu / Tôi ổn",
    category: "Giao tiếp",
  },

  // --- MUA SẮM (SHOPPING) ---
  {
    id: 24,
    japanese: "これはいくらですか？",
    romaji: "Kore wa ikura desu ka?",
    vietnamese: "Cái này bao nhiêu tiền?",
    category: "Mua sắm",
  },
  {
    id: 25,
    japanese: "これをください",
    romaji: "Kore wo kudasai",
    vietnamese: "Cho tôi lấy cái này",
    category: "Mua sắm",
  },
  {
    id: 26,
    japanese: "クレジットカードは使えますか？",
    romaji: "Kurejitto kaado wa tsukaemasu ka?",
    vietnamese: "Có dùng thẻ tín dụng được không?",
    category: "Mua sắm",
  },
  {
    id: 27,
    japanese: "試着してもいいですか？",
    romaji: "Shichaku shitemo ii desu ka?",
    vietnamese: "Tôi thử đồ được không?",
    category: "Mua sắm",
  },
  {
    id: 28,
    japanese: "ちょっと高いです",
    romaji: "Chotto takai desu",
    vietnamese: "Hơi đắt một chút",
    category: "Mua sắm",
  },
  {
    id: 29,
    japanese: "安くしてもらえませんか？",
    romaji: "Yasuku shite moraemasen ka?",
    vietnamese: "Có thể giảm giá không?",
    category: "Mua sắm",
  },
  {
    id: 30,
    japanese: "見ているだけです",
    romaji: "Mite iru dake desu",
    vietnamese: "Tôi chỉ xem thôi",
    category: "Mua sắm",
  },
  {
    id: 31,
    japanese: "これの他の色はありますか？",
    romaji: "Kore no hoka no iro wa arimasu ka?",
    vietnamese: "Cái này có màu khác không?",
    category: "Mua sắm",
  },
  {
    id: 32,
    japanese: "袋はいりません",
    romaji: "Fukuro wa irimasen",
    vietnamese: "Tôi không cần túi",
    category: "Mua sắm",
  },
  {
    id: 33,
    japanese: "レシートをください",
    romaji: "Reshiito wo kudasai",
    vietnamese: "Cho tôi xin hóa đơn",
    category: "Mua sắm",
  },
  {
    id: 34,
    japanese: "免税できますか？",
    romaji: "Menzei dekimasu ka?",
    vietnamese: "Có được miễn thuế không?",
    category: "Mua sắm",
  },

  // --- ĂN UỐNG (DINING) ---
  {
    id: 35,
    japanese: "メニューをください",
    romaji: "Menyuu wo kudasai",
    vietnamese: "Cho tôi xem menu",
    category: "Ăn uống",
  },
  {
    id: 36,
    japanese: "注文をお願いします",
    romaji: "Chuumon wo onegaishimasu",
    vietnamese: "Cho tôi gọi món",
    category: "Ăn uống",
  },
  {
    id: 37,
    japanese: "お水をお願いします",
    romaji: "Omizu wo onegaishimasu",
    vietnamese: "Làm ơn cho tôi nước lọc",
    category: "Ăn uống",
  },
  {
    id: 38,
    japanese: "おすすめは何ですか？",
    romaji: "Osusume wa nan desu ka?",
    vietnamese: "Món gợi ý là gì?",
    category: "Ăn uống",
  },
  {
    id: 39,
    japanese: "これは何ですか？",
    romaji: "Kore wa nan desu ka?",
    vietnamese: "Đây là món gì?",
    category: "Ăn uống",
  },
  {
    id: 40,
    japanese: "辛いですか？",
    romaji: "Karai desu ka?",
    vietnamese: "Có cay không?",
    category: "Ăn uống",
  },
  {
    id: 41,
    japanese: "辛くしないでください",
    romaji: "Karaku shinaide kudasai",
    vietnamese: "Đừng làm cay nhé",
    category: "Ăn uống",
  },
  {
    id: 42,
    japanese: "いただきます",
    romaji: "Itadakimasu",
    vietnamese: "Mời mọi người ăn (nói trước khi ăn)",
    category: "Ăn uống",
  },
  {
    id: 43,
    japanese: "ごちそうさまでした",
    romaji: "Gochisousama deshita",
    vietnamese: "Cảm ơn vì bữa ăn (nói sau khi ăn)",
    category: "Ăn uống",
  },
  {
    id: 44,
    japanese: "お会計をお願いします",
    romaji: "Okaikei wo onegaishimasu",
    vietnamese: "Làm ơn tính tiền",
    category: "Ăn uống",
  },
  {
    id: 45,
    japanese: "とても美味しいです",
    romaji: "Totemo oishii desu",
    vietnamese: "Rất ngon",
    category: "Ăn uống",
  },
  {
    id: 46,
    japanese: "乾杯",
    romaji: "Kanpai",
    vietnamese: "Cạn ly / Dô!",
    category: "Ăn uống",
  },

  // --- DI CHUYỂN & HỎI ĐƯỜNG (TRAVEL & DIRECTIONS) ---
  {
    id: 47,
    japanese: "トイレはどこですか？",
    romaji: "Toire wa doko desu ka?",
    vietnamese: "Nhà vệ sinh ở đâu vậy?",
    category: "Di chuyển",
  },
  {
    id: 48,
    japanese: "駅はどこですか？",
    romaji: "Eki wa doko desu ka?",
    vietnamese: "Nhà ga ở đâu?",
    category: "Di chuyển",
  },
  {
    id: 49,
    japanese: "ここはどこですか？",
    romaji: "Koko wa doko desu ka?",
    vietnamese: "Đây là đâu?",
    category: "Di chuyển",
  },
  {
    id: 50,
    japanese: "タクシー乗り場はどこですか？",
    romaji: "Takushii noriba wa doko desu ka?",
    vietnamese: "Bến taxi ở đâu?",
    category: "Di chuyển",
  },
  {
    id: 51,
    japanese: "このバスはAに行きますか？",
    romaji: "Kono basu wa A ni ikimasu ka?",
    vietnamese: "Xe bus này có đi đến A không?",
    category: "Di chuyển",
  },
  {
    id: 52,
    japanese: "切符をください",
    romaji: "Kippu wo kudasai",
    vietnamese: "Cho tôi mua vé",
    category: "Di chuyển",
  },
  {
    id: 53,
    japanese: "右",
    romaji: "Migi",
    vietnamese: "Phải",
    category: "Di chuyển",
  },
  {
    id: 54,
    japanese: "左",
    romaji: "Hidari",
    vietnamese: "Trái",
    category: "Di chuyển",
  },
  {
    id: 55,
    japanese: "まっすぐ",
    romaji: "Massugu",
    vietnamese: "Đi thẳng",
    category: "Di chuyển",
  },
  {
    id: 56,
    japanese: "地図を書いてくれませんか？",
    romaji: "Chizu wo kaite kuremasen ka?",
    vietnamese: "Bạn vẽ bản đồ giúp tôi được không?",
    category: "Di chuyển",
  },
  {
    id: 57,
    japanese: "歩いて行けますか？",
    romaji: "Aruite ikemasu ka?",
    vietnamese: "Có đi bộ được không?",
    category: "Di chuyển",
  },
  {
    id: 58,
    japanese: "遠いですか？",
    romaji: "Tooi desu ka?",
    vietnamese: "Có xa không?",
    category: "Di chuyển",
  },

  // --- KHÁCH SẠN (HOTEL) ---
  {
    id: 59,
    japanese: "チェックインをお願いします",
    romaji: "Chekku-in wo onegaishimasu",
    vietnamese: "Tôi muốn làm thủ tục nhận phòng",
    category: "Khách sạn",
  },
  {
    id: 60,
    japanese: "予約しています",
    romaji: "Yoyaku shiteimasu",
    vietnamese: "Tôi đã đặt trước rồi",
    category: "Khách sạn",
  },
  {
    id: 61,
    japanese: "Wi-Fiのパスワードは何ですか？",
    romaji: "Wi-Fi no pasuwaado wa nan desu ka?",
    vietnamese: "Mật khẩu Wifi là gì?",
    category: "Khách sạn",
  },
  {
    id: 62,
    japanese: "朝食は何時からですか？",
    romaji: "Choushoku wa nanji kara desu ka?",
    vietnamese: "Bữa sáng bắt đầu từ mấy giờ?",
    category: "Khách sạn",
  },
  {
    id: 63,
    japanese: "荷物を預かってもらえますか？",
    romaji: "Nimotsu wo azukatte moraemasu ka?",
    vietnamese: "Có thể giữ hành lý giúp tôi được không?",
    category: "Khách sạn",
  },
  {
    id: 64,
    japanese: "チェックアウトしたいです",
    romaji: "Chekku-auto shitai desu",
    vietnamese: "Tôi muốn trả phòng",
    category: "Khách sạn",
  },

  // --- KHẨN CẤP (EMERGENCY) ---
  {
    id: 65,
    japanese: "助けて！",
    romaji: "Tasukete!",
    vietnamese: "Cứu tôi với!",
    category: "Khẩn cấp",
  },
  {
    id: 66,
    japanese: "警察を呼んでください",
    romaji: "Keisatsu wo yonde kudasai",
    vietnamese: "Hãy gọi cảnh sát giúp tôi",
    category: "Khẩn cấp",
  },
  {
    id: 67,
    japanese: "救急車を呼んでください",
    romaji: "Kyuukyuusha wo yonde kudasai",
    vietnamese: "Hãy gọi xe cấp cứu",
    category: "Khẩn cấp",
  },
  {
    id: 68,
    japanese: "病院はどこですか？",
    romaji: "Byouin wa doko desu ka?",
    vietnamese: "Bệnh viện ở đâu?",
    category: "Khẩn cấp",
  },
  {
    id: 69,
    japanese: "気分が悪いです",
    romaji: "Kibun ga warui desu",
    vietnamese: "Tôi cảm thấy không khỏe/khó chịu",
    category: "Khẩn cấp",
  },
  {
    id: 70,
    japanese: "パスポートをなくしました",
    romaji: "Pasupooto wo nakushimashita",
    vietnamese: "Tôi bị mất hộ chiếu",
    category: "Khẩn cấp",
  },
  {
    id: 71,
    japanese: "財布を盗まれました",
    romaji: "Saifu wo nusumaremashita",
    vietnamese: "Tôi bị trộm mất ví",
    category: "Khẩn cấp",
  },

  // --- THỜI GIAN & SỐ (TIME & NUMBERS) ---
  {
    id: 72,
    japanese: "今何時ですか？",
    romaji: "Ima nanji desu ka?",
    vietnamese: "Bây giờ là mấy giờ?",
    category: "Khác",
  },
  {
    id: 73,
    japanese: "今日",
    romaji: "Kyou",
    vietnamese: "Hôm nay",
    category: "Khác",
  },
  {
    id: 74,
    japanese: "明日",
    romaji: "Ashita",
    vietnamese: "Ngày mai",
    category: "Khác",
  },
  {
    id: 75,
    japanese: "昨日",
    romaji: "Kinou",
    vietnamese: "Hôm qua",
    category: "Khác",
  },
  {
    id: 76,
    japanese: "毎日",
    romaji: "Mainichi",
    vietnamese: "Mỗi ngày",
    category: "Khác",
  },
  {
    id: 77,
    japanese: "一",
    romaji: "Ichi",
    vietnamese: "Số 1",
    category: "Khác",
  },
  {
    id: 78,
    japanese: "二",
    romaji: "Ni",
    vietnamese: "Số 2",
    category: "Khác",
  },
  {
    id: 79,
    japanese: "三",
    romaji: "San",
    vietnamese: "Số 3",
    category: "Khác",
  },
  {
    id: 80,
    japanese: "十",
    romaji: "Juu",
    vietnamese: "Số 10",
    category: "Khác",
  },
  {
    id: 81,
    japanese: "百",
    romaji: "Hyaku",
    vietnamese: "100",
    category: "Khác",
  },
  {
    id: 82,
    japanese: "千",
    romaji: "Sen",
    vietnamese: "1000",
    category: "Khác",
  },
  {
    id: 83,
    japanese: "万",
    romaji: "Man",
    vietnamese: "10,000 (1 vạn)",
    category: "Khác",
  },

  // --- GIA ĐÌNH (FAMILY) ---
  {
    id: 84,
    japanese: "家族",
    romaji: "Kazoku",
    vietnamese: "Gia đình",
    category: "Gia đình",
  },
  {
    id: 85,
    japanese: "父",
    romaji: "Chichi",
    vietnamese: "Bố (của tôi)",
    category: "Gia đình",
  },
  {
    id: 86,
    japanese: "母",
    romaji: "Haha",
    vietnamese: "Mẹ (của tôi)",
    category: "Gia đình",
  },
  {
    id: 87,
    japanese: "お父さん",
    romaji: "Otousan",
    vietnamese: "Bố (của người khác)",
    category: "Gia đình",
  },
  {
    id: 88,
    japanese: "お母さん",
    romaji: "Okaasan",
    vietnamese: "Mẹ (của người khác)",
    category: "Gia đình",
  },
  {
    id: 89,
    japanese: "兄弟",
    romaji: "Kyoudai",
    vietnamese: "Anh chị em",
    category: "Gia đình",
  },
  {
    id: 90,
    japanese: "兄",
    romaji: "Ani",
    vietnamese: "Anh trai (của tôi)",
    category: "Gia đình",
  },
  {
    id: 91,
    japanese: "姉",
    romaji: "Ane",
    vietnamese: "Chị gái (của tôi)",
    category: "Gia đình",
  },
  {
    id: 92,
    japanese: "弟",
    romaji: "Otouto",
    vietnamese: "Em trai (của tôi)",
    category: "Gia đình",
  },
  {
    id: 93,
    japanese: "妹",
    romaji: "Imouto",
    vietnamese: "Em gái (của tôi)",
    category: "Gia đình",
  },
  {
    id: 94,
    japanese: "結婚しています",
    romaji: "Kekkon shiteimasu",
    vietnamese: "Đã kết hôn",
    category: "Gia đình",
  },
  {
    id: 95,
    japanese: "独身です",
    romaji: "Dokushin desu",
    vietnamese: "Độc thân",
    category: "Gia đình",
  },

  // --- THỜI TIẾT (WEATHER) ---
  {
    id: 96,
    japanese: "天気",
    romaji: "Tenki",
    vietnamese: "Thời tiết",
    category: "Thời tiết",
  },
  {
    id: 97,
    japanese: "春",
    romaji: "Haru",
    vietnamese: "Mùa xuân",
    category: "Thời tiết",
  },
  {
    id: 98,
    japanese: "夏",
    romaji: "Natsu",
    vietnamese: "Mùa hè",
    category: "Thời tiết",
  },
  {
    id: 99,
    japanese: "秋",
    romaji: "Aki",
    vietnamese: "Mùa thu",
    category: "Thời tiết",
  },
  {
    id: 100,
    japanese: "冬",
    romaji: "Fuyu",
    vietnamese: "Mùa đông",
    category: "Thời tiết",
  },
  {
    id: 101,
    japanese: "暑い",
    romaji: "Atsui",
    vietnamese: "Nóng",
    category: "Thời tiết",
  },
  {
    id: 102,
    japanese: "寒い",
    romaji: "Samui",
    vietnamese: "Lạnh",
    category: "Thời tiết",
  },
  {
    id: 103,
    japanese: "雨",
    romaji: "Ame",
    vietnamese: "Mưa",
    category: "Thời tiết",
  },
  {
    id: 104,
    japanese: "雪",
    romaji: "Yuki",
    vietnamese: "Tuyết",
    category: "Thời tiết",
  },
  {
    id: 105,
    japanese: "晴れ",
    romaji: "Hare",
    vietnamese: "Nắng / Quang đãng",
    category: "Thời tiết",
  },

  // --- CÔNG VIỆC (WORK) ---
  {
    id: 106,
    japanese: "会社",
    romaji: "Kaisha",
    vietnamese: "Công ty",
    category: "Công việc",
  },
  {
    id: 107,
    japanese: "仕事",
    romaji: "Shigoto",
    vietnamese: "Công việc",
    category: "Công việc",
  },
  {
    id: 108,
    japanese: "会社員",
    romaji: "Kaishain",
    vietnamese: "Nhân viên công ty",
    category: "Công việc",
  },
  {
    id: 109,
    japanese: "会議",
    romaji: "Kaigi",
    vietnamese: "Cuộc họp",
    category: "Công việc",
  },
  {
    id: 110,
    japanese: "残業",
    romaji: "Zangyou",
    vietnamese: "Làm thêm giờ",
    category: "Công việc",
  },
  {
    id: 111,
    japanese: "電話",
    romaji: "Denwa",
    vietnamese: "Điện thoại",
    category: "Công việc",
  },
  {
    id: 112,
    japanese: "名刺",
    romaji: "Meishi",
    vietnamese: "Danh thiếp",
    category: "Công việc",
  },
  {
    id: 113,
    japanese: "パソコン",
    romaji: "Pasokon",
    vietnamese: "Máy tính cá nhân",
    category: "Công việc",
  },
  {
    id: 114,
    japanese: "休憩",
    romaji: "Kyuukei",
    vietnamese: "Nghỉ giải lao",
    category: "Công việc",
  },
  {
    id: 115,
    japanese: "お疲れ様です",
    romaji: "Otsukaresama desu",
    vietnamese: "Chào hỏi khi làm việc (Cảm ơn vì đã vất vả)",
    category: "Công việc",
  },
];

export const conversations: Conversation[] = [
  // --- CHÀO HỎI (GREETINGS) ---
  {
    id: 201,
    title: "Chào hỏi giáo viên",
    category: "Chào hỏi",
    lines: [
      {
        role: "A",
        japanese: "先生、おはようございます。",
        romaji: "Sensei, ohayou gozaimasu.",
        vietnamese: "Chào buổi sáng cô giáo.",
      },
      {
        role: "B",
        japanese: "おはよう、アンさん。元気ですか？",
        romaji: "Ohayou, An-san. Genki desu ka?",
        vietnamese: "Chào buổi sáng, An. Em có khỏe không?",
      },
      {
        role: "A",
        japanese: "はい、元気です。",
        romaji: "Hai, genki desu.",
        vietnamese: "Vâng, em khỏe ạ.",
      },
    ],
  },
  {
    id: 202,
    title: "Chào tạm biệt bạn bè",
    category: "Chào hỏi",
    lines: [
      {
        role: "A",
        japanese: "じゃあ、また明日。",
        romaji: "Jaa, mata ashita.",
        vietnamese: "Vậy, mai gặp nhé.",
      },
      {
        role: "B",
        japanese: "うん、またね。",
        romaji: "Un, mata ne.",
        vietnamese: "Ừ, hẹn gặp lại.",
      },
    ],
  },
  {
    id: 203,
    title: "Gặp hàng xóm",
    category: "Chào hỏi",
    lines: [
      {
        role: "A",
        japanese: "こんにちは、いい天気ですね。",
        romaji: "Konnichiwa, ii tenki desu ne.",
        vietnamese: "Xin chào, thời tiết đẹp nhỉ.",
      },
      {
        role: "B",
        japanese: "そうですね。お出かけですか？",
        romaji: "Sou desu ne. Odekake desu ka?",
        vietnamese: "Đúng vậy. Bạn đi ra ngoài à?",
      },
      {
        role: "A",
        japanese: "ええ、ちょっとスーパーまで。",
        romaji: "Ee, chotto suupaa made.",
        vietnamese: "Vâng, tôi ra siêu thị một chút.",
      },
    ],
  },
  {
    id: 204,
    title: "Lâu ngày không gặp",
    category: "Chào hỏi",
    lines: [
      {
        role: "A",
        japanese: "お久しぶりです。",
        romaji: "Ohisashiburi desu.",
        vietnamese: "Lâu rồi không gặp.",
      },
      {
        role: "B",
        japanese: "あ、田中さん！お元気でしたか？",
        romaji: "A, Tanaka-san! Ogenki deshita ka?",
        vietnamese: "A, Tanaka! Bạn vẫn khỏe chứ?",
      },
      {
        role: "A",
        japanese: "はい、おかげさまで。",
        romaji: "Hai, okagesama de.",
        vietnamese: "Vâng, trộm vía tôi vẫn khỏe.",
      },
    ],
  },
  {
    id: 205,
    title: "Chào khách đến nhà",
    category: "Chào hỏi",
    lines: [
      {
        role: "A",
        japanese: "いらっしゃい。どうぞ上がってください。",
        romaji: "Irasshai. Douzo agatte kudasai.",
        vietnamese: "Chào mừng. Mời vào nhà.",
      },
      {
        role: "B",
        japanese: "お邪魔します。",
        romaji: "Ojama shimasu.",
        vietnamese: "Xin phép làm phiền ạ.",
      },
    ],
  },

  // --- GIỚI THIỆU (SELF INTRO) ---
  {
    id: 301,
    title: "Giới thiệu bản thân ngắn gọn",
    category: "Giới thiệu",
    lines: [
      {
        role: "A",
        japanese: "はじめまして、私はミンです。",
        romaji: "Hajimemashite, watashi wa Min desu.",
        vietnamese: "Chào bạn, tôi là Minh.",
      },
      {
        role: "B",
        japanese: "私はケンです。よろしく。",
        romaji: "Watashi wa Ken desu. Yoroshiku.",
        vietnamese: "Tôi là Ken. Rất vui được gặp.",
      },
    ],
  },
  {
    id: 302,
    title: "Giới thiệu người khác",
    category: "Giới thiệu",
    lines: [
      {
        role: "A",
        japanese: "こちらは私の友達のアンさんです。",
        romaji: "Kochira wa watashi no tomodachi no An-san desu.",
        vietnamese: "Đây là bạn tôi, An.",
      },
      {
        role: "B",
        japanese: "はじめまして、アンです。",
        romaji: "Hajimemashite, An desu.",
        vietnamese: "Rất vui được gặp, tôi là An.",
      },
      {
        role: "C",
        japanese: "はじめまして。",
        romaji: "Hajimemashite.",
        vietnamese: "Chào bạn.",
      },
    ],
  },
  {
    id: 303,
    title: "Trao đổi danh thiếp",
    category: "Giới thiệu",
    lines: [
      {
        role: "A",
        japanese: "初めまして。私はABC会社の佐藤です。",
        romaji: "Hajimemashite. Watashi wa ABC kaisha no Satou desu.",
        vietnamese: "Xin chào. Tôi là Satou từ công ty ABC.",
      },
      {
        role: "B",
        japanese: "初めまして。こちらが私の名刺です。",
        romaji: "Hajimemashite. Kochira ga watashi no meishi desu.",
        vietnamese: "Chào bạn. Đây là danh thiếp của tôi.",
      },
      {
        role: "A",
        japanese: "頂戴いたします。",
        romaji: "Choudai itashimasu.",
        vietnamese: "Tôi xin nhận ạ.",
      },
    ],
  },
  {
    id: 304,
    title: "Hỏi tuổi",
    category: "Giới thiệu",
    lines: [
      {
        role: "A",
        japanese: "失礼ですが、おいくつですか？",
        romaji: "Shitsurei desu ga, oikutsu desu ka?",
        vietnamese: "Xin lỗi, bạn bao nhiêu tuổi?",
      },
      {
        role: "B",
        japanese: "25歳です。",
        romaji: "Nijuugo-sai desu.",
        vietnamese: "Tôi 25 tuổi.",
      },
      {
        role: "A",
        japanese: "私と同じですね。",
        romaji: "Watashi to onaji desu ne.",
        vietnamese: "Bằng tuổi tôi nhỉ.",
      },
    ],
  },
  {
    id: 305,
    title: "Nói về nghề nghiệp",
    category: "Giới thiệu",
    lines: [
      {
        role: "A",
        japanese: "お仕事は何ですか？",
        romaji: "Oshigoto wa nan desu ka?",
        vietnamese: "Bạn làm nghề gì?",
      },
      {
        role: "B",
        japanese: "エンジニアです。あなたは？",
        romaji: "Enjinia desu. Anata wa?",
        vietnamese: "Tôi là kỹ sư. Còn bạn?",
      },
      {
        role: "A",
        japanese: "私は教師です。",
        romaji: "Watashi wa kyoushi desu.",
        vietnamese: "Tôi là giáo viên.",
      },
    ],
  },

  // --- GIAO TIẾP (COMMUNICATION) ---
  {
    id: 1,
    title: "Làm quen cơ bản",
    category: "Giao tiếp",
    lines: [
      {
        role: "A",
        japanese: "こんにちは。お名前は何ですか？",
        romaji: "Konnichiwa. Onamae wa nan desu ka?",
        vietnamese: "Xin chào. Tên bạn là gì?",
      },
      {
        role: "B",
        japanese: "こんにちは。私はタインです。",
        romaji: "Konnichiwa. Watashi wa Tain desu.",
        vietnamese: "Chào bạn. Tôi là Thành.",
      },
      {
        role: "A",
        japanese: "タインさんですね。私は田中です。",
        romaji: "Tain-san desu ne. Watashi wa Tanaka desu.",
        vietnamese: "Bạn Thành nhỉ. Tôi là Tanaka.",
      },
      {
        role: "B",
        japanese: "はじめまして。よろしくお願いします。",
        romaji: "Hajimemashite. Yoroshiku onegaishimasu.",
        vietnamese: "Rất vui được gặp. Mong được giúp đỡ.",
      },
    ],
  },
  {
    id: 2,
    title: "Hỏi thăm sức khỏe",
    category: "Giao tiếp",
    lines: [
      {
        role: "A",
        japanese: "お元気ですか？",
        romaji: "Ogenki desu ka?",
        vietnamese: "Bạn có khỏe không?",
      },
      {
        role: "B",
        japanese: "はい、元気です。あなたは？",
        romaji: "Hai, genki desu. Anata wa?",
        vietnamese: "Vâng, tôi khỏe. Còn bạn?",
      },
      {
        role: "A",
        japanese: "私も元気です。ありがとうございます。",
        romaji: "Watashi mo genki desu. Arigatou gozaimasu.",
        vietnamese: "Tôi cũng khỏe. Cảm ơn bạn.",
      },
    ],
  },
  {
    id: 3,
    title: "Nói về sở thích",
    category: "Giao tiếp",
    lines: [
      {
        role: "A",
        japanese: "趣味は何ですか？",
        romaji: "Shumi wa nan desu ka?",
        vietnamese: "Sở thích của bạn là gì?",
      },
      {
        role: "B",
        japanese: "映画を見ることです。あなたは？",
        romaji: "Eiga wo miru koto desu. Anata wa?",
        vietnamese: "Là xem phim. Còn bạn?",
      },
      {
        role: "A",
        japanese: "私はサッカーが好きです。",
        romaji: "Watashi wa sakkaa ga suki desu.",
        vietnamese: "Tôi thích bóng đá.",
      },
    ],
  },
  {
    id: 4,
    title: "Hỏi quê quán",
    category: "Giao tiếp",
    lines: [
      {
        role: "A",
        japanese: "どこから来ましたか？",
        romaji: "Doko kara kimashita ka?",
        vietnamese: "Bạn đến từ đâu?",
      },
      {
        role: "B",
        japanese: "ベトナムのハノイから来ました。",
        romaji: "Betonamu no Hanoi kara kimashita.",
        vietnamese: "Tôi đến từ Hà Nội, Việt Nam.",
      },
      {
        role: "A",
        japanese: "そうですか。いいところですね。",
        romaji: "Sou desu ka. Ii tokoro desu ne.",
        vietnamese: "Vậy à. Đó là một nơi tuyệt vời nhỉ.",
      },
    ],
  },
  {
    id: 5,
    title: "Nhờ chụp ảnh giúp",
    category: "Giao tiếp",
    lines: [
      {
        role: "A",
        japanese: "すみません、写真を撮ってもらえますか？",
        romaji: "Sumimasen, shashin wo totte moraemasu ka?",
        vietnamese: "Xin lỗi, chụp giúp tôi tấm ảnh được không?",
      },
      {
        role: "B",
        japanese: "いいですよ。はい、チーズ！",
        romaji: "Ii desu yo. Hai, chiizu!",
        vietnamese: "Được chứ. Nào, cười lên!",
      },
      {
        role: "A",
        japanese: "ありがとうございます。",
        romaji: "Arigatou gozaimasu.",
        vietnamese: "Cảm ơn bạn nhiều.",
      },
    ],
  },

  // --- DI CHUYỂN (TRAVEL) ---
  {
    id: 6,
    title: "Hỏi đường đến nhà ga",
    category: "Di chuyển",
    lines: [
      {
        role: "A",
        japanese: "すみません。駅はどこですか？",
        romaji: "Sumimasen. Eki wa doko desu ka?",
        vietnamese: "Xin lỗi. Nhà ga ở đâu vậy?",
      },
      {
        role: "B",
        japanese: "まっすぐ行って、右に曲がってください。",
        romaji: "Massugu itte, migi ni magatte kudasai.",
        vietnamese: "Đi thẳng, rồi rẽ phải nhé.",
      },
      {
        role: "A",
        japanese: "ここから遠いですか？",
        romaji: "Koko kara tooi desu ka?",
        vietnamese: "Từ đây có xa không?",
      },
      {
        role: "B",
        japanese: "いいえ、歩いて5分くらいです。",
        romaji: "Iie, aruite go-fun kurai desu.",
        vietnamese: "Không, đi bộ khoảng 5 phút thôi.",
      },
    ],
  },
  {
    id: 7,
    title: "Đi taxi",
    category: "Di chuyển",
    lines: [
      {
        role: "A",
        japanese: "東京駅までお願いします。",
        romaji: "Toukyou-eki made onegaishimasu.",
        vietnamese: "Làm ơn đưa tôi đến ga Tokyo.",
      },
      {
        role: "B",
        japanese: "はい、わかりました。",
        romaji: "Hai, wakarimashita.",
        vietnamese: "Vâng, tôi hiểu rồi.",
      },
      {
        role: "A",
        japanese: "ここで下ろしてください。",
        romaji: "Koko de oroshite kudasai.",
        vietnamese: "Hãy cho tôi xuống tại đây.",
      },
      {
        role: "B",
        japanese: "はい、1500円です。",
        romaji: "Hai, sen-gohyakuen desu.",
        vietnamese: "Vâng, hết 1500 yên.",
      },
    ],
  },
  {
    id: 8,
    title: "Mua vé tàu",
    category: "Di chuyển",
    lines: [
      {
        role: "A",
        japanese: "新宿までの切符をください。",
        romaji: "Shinjuku made no kippu wo kudasai.",
        vietnamese: "Cho tôi vé đến Shinjuku.",
      },
      {
        role: "B",
        japanese: "大人一人ですか？",
        romaji: "Otona hitori desu ka?",
        vietnamese: "Một người lớn phải không?",
      },
      {
        role: "A",
        japanese: "はい、そうです。いくらですか？",
        romaji: "Hai, sou desu. Ikura desu ka?",
        vietnamese: "Vâng đúng rồi. Bao nhiêu tiền?",
      },
      {
        role: "B",
        japanese: "200円です。",
        romaji: "Nihyaku-en desu.",
        vietnamese: "200 yên.",
      },
    ],
  },
  {
    id: 9,
    title: "Hỏi xe buýt",
    category: "Di chuyển",
    lines: [
      {
        role: "A",
        japanese: "このバスは京都に行きますか？",
        romaji: "Kono basu wa Kyouto ni ikimasu ka?",
        vietnamese: "Xe bus này có đi Kyoto không?",
      },
      {
        role: "B",
        japanese: "いいえ、行きません。次のバスですよ。",
        romaji: "Iie, ikimasen. Tsugi no basu desu yo.",
        vietnamese: "Không, không đi. Là chuyến xe tiếp theo cơ.",
      },
      {
        role: "A",
        japanese: "何時に来ますか？",
        romaji: "Nanji ni kimasu ka?",
        vietnamese: "Mấy giờ xe đến?",
      },
      {
        role: "B",
        japanese: "10時半です。",
        romaji: "Juujihan desu.",
        vietnamese: "Lúc 10 rưỡi.",
      },
    ],
  },
  {
    id: 60,
    title: "Hỏi đường đến ngân hàng",
    category: "Di chuyển",
    lines: [
      {
        role: "A",
        japanese: "すみません、近くに銀行はありますか？",
        romaji: "Sumimasen, chikaku ni ginkou wa arimasu ka?",
        vietnamese: "Xin lỗi, gần đây có ngân hàng nào không?",
      },
      {
        role: "B",
        japanese: "はい、あそこのコンビニの隣です。",
        romaji: "Hai, asoko no konbini no tonari desu.",
        vietnamese: "Có, ở bên cạnh cửa hàng tiện lợi kia.",
      },
      {
        role: "A",
        japanese: "ありがとうございます。",
        romaji: "Arigatou gozaimasu.",
        vietnamese: "Cảm ơn bạn.",
      },
    ],
  },

  // --- MUA SẮM (SHOPPING) ---
  {
    id: 10,
    title: "Mua sắm tại cửa hàng",
    category: "Mua sắm",
    lines: [
      {
        role: "A",
        japanese: "いらっしゃいませ。",
        romaji: "Irasshaimase.",
        vietnamese: "Kính chào quý khách.",
      },
      {
        role: "B",
        japanese: "これを見てもいいですか？",
        romaji: "Kore wo mite mo ii desu ka?",
        vietnamese: "Tôi xem cái này được không?",
      },
      {
        role: "A",
        japanese: "はい、どうぞ。",
        romaji: "Hai, douzo.",
        vietnamese: "Vâng, xin mời.",
      },
      {
        role: "B",
        japanese: "いくらですか？",
        romaji: "Ikura desu ka?",
        vietnamese: "Bao nhiêu tiền vậy?",
      },
      {
        role: "A",
        japanese: "2000円です。",
        romaji: "Nisen-en desu.",
        vietnamese: "2000 yên.",
      },
    ],
  },
  {
    id: 11,
    title: "Thử quần áo",
    category: "Mua sắm",
    lines: [
      {
        role: "A",
        japanese: "試着してもいいですか？",
        romaji: "Shichaku shitemo ii desu ka?",
        vietnamese: "Tôi thử đồ được không?",
      },
      {
        role: "B",
        japanese: "はい、試着室はこちらです。",
        romaji: "Hai, shichakushitsu wa kochira desu.",
        vietnamese: "Vâng, phòng thử đồ ở hướng này.",
      },
      {
        role: "A",
        japanese: "少し大きいです。Sサイズはありますか？",
        romaji: "Sukoshi ookii desu. S-saizu wa arimasu ka?",
        vietnamese: "Hơi rộng. Có size S không?",
      },
      {
        role: "B",
        japanese: "はい、少々お待ちください。",
        romaji: "Hai, shoushou omachi kudasai.",
        vietnamese: "Vâng, xin chờ một chút.",
      },
    ],
  },
  {
    id: 12,
    title: "Mặc cả",
    category: "Mua sắm",
    lines: [
      {
        role: "A",
        japanese: "これはちょっと高いですね。",
        romaji: "Kore wa chotto takai desu ne.",
        vietnamese: "Cái này hơi đắt nhỉ.",
      },
      {
        role: "B",
        japanese: "いい商品ですよ。",
        romaji: "Ii shouhin desu yo.",
        vietnamese: "Sản phẩm tốt lắm đấy ạ.",
      },
      {
        role: "A",
        japanese: "安くしてもらえませんか？",
        romaji: "Yasuku shite moraemasen ka?",
        vietnamese: "Có thể giảm giá không?",
      },
      {
        role: "B",
        japanese: "じゃあ、3000円でどうですか？",
        romaji: "Jaa, sanzen-en de dou desu ka?",
        vietnamese: "Vậy 3000 yên thì sao?",
      },
    ],
  },
  {
    id: 13,
    title: "Tại cửa hàng tiện lợi (Konbini)",
    category: "Mua sắm",
    lines: [
      {
        role: "A",
        japanese: "お弁当温めますか？",
        romaji: "Obentou atatamemasu ka?",
        vietnamese: "Có hâm nóng cơm hộp không ạ?",
      },
      {
        role: "B",
        japanese: "はい、お願いします。",
        romaji: "Hai, onegaishimasu.",
        vietnamese: "Vâng, làm ơn.",
      },
      {
        role: "A",
        japanese: "袋はいりますか？",
        romaji: "Fukuro wa irimasu ka?",
        vietnamese: "Có lấy túi không ạ?",
      },
      {
        role: "B",
        japanese: "いいえ、結構です。",
        romaji: "Iie, kekkou desu.",
        vietnamese: "Không, tôi đủ rồi.",
      },
    ],
  },
  {
    id: 80,
    title: "Tìm quầy bán giày",
    category: "Mua sắm",
    lines: [
      {
        role: "A",
        japanese: "すみません、靴売り場はどこですか？",
        romaji: "Sumimasen, kutsu uriba wa doko desu ka?",
        vietnamese: "Xin lỗi, quầy bán giày ở đâu?",
      },
      {
        role: "B",
        japanese: "3階にございます。",
        romaji: "Sangai ni gozaimasu.",
        vietnamese: "Ở tầng 3 ạ.",
      },
    ],
  },

  // --- ĂN UỐNG (DINING) ---
  {
    id: 14,
    title: "Gọi món tại nhà hàng",
    category: "Ăn uống",
    lines: [
      {
        role: "A",
        japanese: "ご注文はお決まりですか？",
        romaji: "Gochuumon wa okimari desu ka?",
        vietnamese: "Quý khách đã quyết định gọi món chưa?",
      },
      {
        role: "B",
        japanese: "おすすめは何ですか？",
        romaji: "Osusume wa nan desu ka?",
        vietnamese: "Món gợi ý là gì vậy?",
      },
      {
        role: "A",
        japanese: "天ぷらが美味しいですよ。",
        romaji: "Tempura ga oishii desu yo.",
        vietnamese: "Món Tempura ngon lắm đấy.",
      },
      {
        role: "B",
        japanese: "じゃ、天ぷらをください。",
        romaji: "Ja, tempura wo kudasai.",
        vietnamese: "Vậy cho tôi Tempura nhé.",
      },
    ],
  },
  {
    id: 15,
    title: "Đặt bàn trước",
    category: "Ăn uống",
    lines: [
      {
        role: "A",
        japanese: "予約をしたいのですが。",
        romaji: "Yoyaku wo shitai no desu ga.",
        vietnamese: "Tôi muốn đặt bàn.",
      },
      {
        role: "B",
        japanese: "何名様ですか？",
        romaji: "Nanmeisama desu ka?",
        vietnamese: "Đi mấy người ạ?",
      },
      {
        role: "A",
        japanese: "二人です。今夜7時にお願いします。",
        romaji: "Futari desu. Konya shichiji ni onegaishimasu.",
        vietnamese: "2 người. 7 giờ tối nay nhé.",
      },
      {
        role: "B",
        japanese: "かしこまりました。",
        romaji: "Kashikomarimashita.",
        vietnamese: "Vâng tôi đã hiểu.",
      },
    ],
  },
  {
    id: 16,
    title: "Hỏi về dị ứng",
    category: "Ăn uống",
    lines: [
      {
        role: "A",
        japanese: "この料理にエビは入っていますか？",
        romaji: "Kono ryouri ni ebi wa haitteimasu ka?",
        vietnamese: "Món này có tôm không?",
      },
      {
        role: "B",
        japanese: "いいえ、入っていません。",
        romaji: "Iie, haitteimasen.",
        vietnamese: "Không, không có đâu ạ.",
      },
      {
        role: "A",
        japanese: "私はエビのアレルギーがあります。",
        romaji: "Watashi wa ebi no arerugii ga arimasu.",
        vietnamese: "Tôi bị dị ứng tôm.",
      },
      {
        role: "B",
        japanese: "わかりました。気をつつけます。",
        romaji: "Wakarimashita. Ki wo tsukemasu.",
        vietnamese: "Tôi hiểu rồi. Tôi sẽ lưu ý.",
      },
    ],
  },
  {
    id: 17,
    title: "Thanh toán",
    category: "Ăn uống",
    lines: [
      {
        role: "A",
        japanese: "お会計をお願いします。",
        romaji: "Okaikei wo onegaishimasu.",
        vietnamese: "Làm ơn tính tiền.",
      },
      {
        role: "B",
        japanese: "ご一緒でよろしいですか？",
        romaji: "Goissho de yoroshii desu ka?",
        vietnamese: "Thanh toán chung đúng không ạ?",
      },
      {
        role: "A",
        japanese: "別々にお願いします。",
        romaji: "Betsubetsu ni onegaishimasu.",
        vietnamese: "Làm ơn tính riêng ra.",
      },
      {
        role: "B",
        japanese: "はい、承知いたしました。",
        romaji: "Hai, shouchi itashimashita.",
        vietnamese: "Vâng, tôi hiểu rồi.",
      },
    ],
  },
  {
    id: 90,
    title: "Đặt món tráng miệng",
    category: "Ăn uống",
    lines: [
      {
        role: "A",
        japanese: "デザートはいかがですか？",
        romaji: "Dezaato wa ikaga desu ka?",
        vietnamese: "Quý khách có dùng tráng miệng không?",
      },
      {
        role: "B",
        japanese: "アイスクリームをお願いします。",
        romaji: "Aisukuriimu wo onegaishimasu.",
        vietnamese: "Cho tôi kem nhé.",
      },
    ],
  },

  // --- KHÁCH SẠN (HOTEL) ---
  {
    id: 18,
    title: "Check-in nhận phòng",
    category: "Khách sạn",
    lines: [
      {
        role: "A",
        japanese: "チェックインをお願いします。",
        romaji: "Chekku-in wo onegaishimasu.",
        vietnamese: "Tôi muốn check-in.",
      },
      {
        role: "B",
        japanese: "お名前をお書きください。",
        romaji: "Onamae wo okaki kudasai.",
        vietnamese: "Xin vui lòng viết tên vào đây.",
      },
      {
        role: "A",
        japanese: "はい、これでいいですか？",
        romaji: "Hai, kore de ii desu ka?",
        vietnamese: "Vâng, thế này được chưa?",
      },
      {
        role: "B",
        japanese: "はい、これが鍵です。305号室です。",
        romaji: "Hai, kore ga kagi desu. San-maru-go goushitsu desu.",
        vietnamese: "Vâng, đây là chìa khóa. Phòng 305.",
      },
    ],
  },
  {
    id: 19,
    title: "Báo cáo sự cố phòng",
    category: "Khách sạn",
    lines: [
      {
        role: "A",
        japanese: "すみません、お湯が出ません。",
        romaji: "Sumimasen, oyu ga demasen.",
        vietnamese: "Xin lỗi, không có nước nóng.",
      },
      {
        role: "B",
        japanese: "申し訳ありません。すぐ確認します。",
        romaji: "Moushiwake arimasen. Sugu kakunin shimasu.",
        vietnamese: "Thành thật xin lỗi. Tôi sẽ kiểm tra ngay.",
      },
      {
        role: "A",
        japanese: "お願いします。",
        romaji: "Onegaishimasu.",
        vietnamese: "Làm ơn nhé.",
      },
    ],
  },
  {
    id: 20,
    title: "Gửi hành lý",
    category: "Khách sạn",
    lines: [
      {
        role: "A",
        japanese: "チェックアウト後も荷物を預けられますか？",
        romaji: "Chekku-auto go mo nimotsu wo azukeraremasu ka?",
        vietnamese: "Sau khi trả phòng tôi gửi hành lý được không?",
      },
      {
        role: "B",
        japanese: "はい、何時までですか？",
        romaji: "Hai, nanji made desu ka?",
        vietnamese: "Vâng, đến mấy giờ ạ?",
      },
      {
        role: "A",
        japanese: "夕方の5時までお願いします。",
        romaji: "Yuugata no goji made onegaishimasu.",
        vietnamese: "Đến 5 giờ chiều.",
      },
    ],
  },
  {
    id: 21,
    title: "Check-out trả phòng",
    category: "Khách sạn",
    lines: [
      {
        role: "A",
        japanese: "チェックアウトしたいです。",
        romaji: "Chekku-auto shitai desu.",
        vietnamese: "Tôi muốn trả phòng.",
      },
      {
        role: "B",
        japanese: "ミニバーは利用しましたか？",
        romaji: "Minibaa wa riyou shimashita ka?",
        vietnamese: "Quý khách có dùng đồ uống trong tủ lạnh không?",
      },
      {
        role: "A",
        japanese: "いいえ、使っていません。",
        romaji: "Iie, tsukatteimasen.",
        vietnamese: "Không, tôi không dùng.",
      },
      {
        role: "B",
        japanese: "ありがとうございます。",
        romaji: "Arigatou gozaimasu.",
        vietnamese: "Cảm ơn quý khách.",
      },
    ],
  },
  {
    id: 100,
    title: "Hỏi dịch vụ giặt ủi",
    category: "Khách sạn",
    lines: [
      {
        role: "A",
        japanese: "ランドリーサービスはありますか？",
        romaji: "Randorii saabisu wa arimasu ka?",
        vietnamese: "Có dịch vụ giặt ủi không?",
      },
      {
        role: "B",
        japanese: "はい、袋に入れてください。",
        romaji: "Hai, fukuro ni irete kudasai.",
        vietnamese: "Có, xin hãy bỏ vào túi này.",
      },
    ],
  },

  // --- KHẨN CẤP & SỨC KHỎE (EMERGENCY) ---
  {
    id: 22,
    title: "Mất đồ",
    category: "Khẩn cấp",
    lines: [
      {
        role: "A",
        japanese: "すみません、財布をなくしました。",
        romaji: "Sumimasen, saifu wo nakushimashita.",
        vietnamese: "Xin lỗi, tôi bị mất ví.",
      },
      {
        role: "B",
        japanese: "どこでなくしましたか？",
        romaji: "Doko de nakushimashita ka?",
        vietnamese: "Bạn mất ở đâu?",
      },
      {
        role: "A",
        japanese: "多分、電車の中です。",
        romaji: "Tabun, densha no naka desu.",
        vietnamese: "Có lẽ là ở trên tàu điện.",
      },
      {
        role: "B",
        japanese: "駅の事務所に行ってみましょう。",
        romaji: "Eki no jimusho ni itte mimashou.",
        vietnamese: "Hãy thử đến văn phòng nhà ga xem sao.",
      },
    ],
  },
  {
    id: 23,
    title: "Mua thuốc",
    category: "Khẩn cấp",
    lines: [
      {
        role: "A",
        japanese: "頭が痛いです。薬はありますか？",
        romaji: "Atama ga itai desu. Kusuri wa arimasu ka?",
        vietnamese: "Tôi bị đau đầu. Có thuốc không?",
      },
      {
        role: "B",
        japanese: "はい、こちらの鎮痛剤がいいですよ。",
        romaji: "Hai, kochira no chintsuuzai ga ii desu yo.",
        vietnamese: "Vâng, thuốc giảm đau này tốt đấy.",
      },
      {
        role: "A",
        japanese: "眠くなりますか？",
        romaji: "Nemuku narimasu ka?",
        vietnamese: "Có gây buồn ngủ không?",
      },
      {
        role: "B",
        japanese: "少し眠くなるかもしれません。",
        romaji: "Sukoshi nemuku naru kamo shiremasen.",
        vietnamese: "Có thể sẽ hơi buồn ngủ một chút.",
      },
    ],
  },
  {
    id: 24,
    title: "Cảm thấy không khỏe",
    category: "Khẩn cấp",
    lines: [
      {
        role: "A",
        japanese: "気分が悪いです。",
        romaji: "Kibun ga warui desu.",
        vietnamese: "Tôi cảm thấy không khỏe.",
      },
      {
        role: "B",
        japanese: "大丈夫ですか？座りますか？",
        romaji: "Daijoubu desu ka? Suwarimasu ka?",
        vietnamese: "Bạn ổn không? Có muốn ngồi không?",
      },
      {
        role: "A",
        japanese: "はい、水をください。",
        romaji: "Hai, mizu wo kudasai.",
        vietnamese: "Vâng, cho tôi xin nước.",
      },
      {
        role: "B",
        japanese: "救急車を呼びましょうか？",
        romaji: "Kyuukyuusha wo yobimashou ka?",
        vietnamese: "Tôi gọi xe cấp cứu nhé?",
      },
    ],
  },
  {
    id: 110,
    title: "Bị thương",
    category: "Khẩn cấp",
    lines: [
      {
        role: "A",
        japanese: "足に怪我をしました。",
        romaji: "Ashi ni kega wo shimashita.",
        vietnamese: "Tôi bị thương ở chân.",
      },
      {
        role: "B",
        japanese: "血が出ていますね。病院へ行きましょう。",
        romaji: "Chi ga deteimasu ne. Byouin e ikimashou.",
        vietnamese: "Đang chảy máu đấy. Đi bệnh viện thôi.",
      },
    ],
  },
  {
    id: 111,
    title: "Báo cháy",
    category: "Khẩn cấp",
    lines: [
      {
        role: "A",
        japanese: "火事だ！逃げろ！",
        romaji: "Kaji da! Nigero!",
        vietnamese: "Cháy rồi! Chạy đi!",
      },
      {
        role: "B",
        japanese: "消防車を呼んで！",
        romaji: "Shoubousha wo yonde!",
        vietnamese: "Gọi xe cứu hỏa đi!",
      },
    ],
  },

  // --- KHÁC (OTHERS: TIME/DATE) ---
  {
    id: 401,
    title: "Hỏi ngày tháng",
    category: "Khác",
    lines: [
      {
        role: "A",
        japanese: "今日は何日ですか？",
        romaji: "Kyou wa nannichi desu ka?",
        vietnamese: "Hôm nay là ngày mấy?",
      },
      {
        role: "B",
        japanese: "12月20日です。",
        romaji: "Juuni-gatsu hatsuka desu.",
        vietnamese: "Là ngày 20 tháng 12.",
      },
      {
        role: "A",
        japanese: "ありがとうございます。",
        romaji: "Arigatou gozaimasu.",
        vietnamese: "Cảm ơn bạn.",
      },
    ],
  },
  {
    id: 402,
    title: "Hỏi giờ",
    category: "Khác",
    lines: [
      {
        role: "A",
        japanese: "すみません、今何時ですか？",
        romaji: "Sumimasen, ima nanji desu ka?",
        vietnamese: "Xin lỗi, bây giờ là mấy giờ?",
      },
      {
        role: "B",
        japanese: "午後3時半です。",
        romaji: "Gogo sanji-han desu.",
        vietnamese: "Là 3 rưỡi chiều.",
      },
    ],
  },
  {
    id: 403,
    title: "Sinh nhật",
    category: "Khác",
    lines: [
      {
        role: "A",
        japanese: "誕生日はいつですか？",
        romaji: "Tanjoubi wa itsu desu ka?",
        vietnamese: "Sinh nhật bạn khi nào?",
      },
      {
        role: "B",
        japanese: "5月5日です。",
        romaji: "Gogatsu itsuka desu.",
        vietnamese: "Ngày 5 tháng 5.",
      },
    ],
  },
  {
    id: 404,
    title: "Hỏi số lượng",
    category: "Khác",
    lines: [
      {
        role: "A",
        japanese: "りんごがいくつありますか？",
        romaji: "Ringo ga ikutsu arimasu ka?",
        vietnamese: "Có bao nhiêu quả táo?",
      },
      {
        role: "B",
        japanese: "3つあります。",
        romaji: "Mittsu arimasu.",
        vietnamese: "Có 3 quả.",
      },
    ],
  },
  {
    id: 405,
    title: "Hỏi khoảng cách",
    category: "Khác",
    lines: [
      {
        role: "A",
        japanese: "ここから学校までどのくらいですか？",
        romaji: "Koko kara gakkou made dono kurai desu ka?",
        vietnamese: "Từ đây đến trường mất bao lâu?",
      },
      {
        role: "B",
        japanese: "バスで10分くらいです。",
        romaji: "Basu de juppun kurai desu.",
        vietnamese: "Đi xe buýt khoảng 10 phút.",
      },
    ],
  },

  // --- GIA ĐÌNH (FAMILY) ---
  {
    id: 501,
    title: "Nói về gia đình",
    category: "Gia đình",
    lines: [
      {
        role: "A",
        japanese: "何人家族ですか？",
        romaji: "Nannin kazoku desu ka?",
        vietnamese: "Gia đình bạn có mấy người?",
      },
      {
        role: "B",
        japanese: "4人です。父と母と姉と私です。",
        romaji: "Yonin desu. Chichi to haha to ane to watashi desu.",
        vietnamese: "4 người. Bố, mẹ, chị gái và tôi.",
      },
      {
        role: "A",
        japanese: "お姉さんは何をしていますか？",
        romaji: "Oneesan wa nani wo shiteimasu ka?",
        vietnamese: "Chị gái bạn làm nghề gì?",
      },
      {
        role: "B",
        japanese: "大学生です。",
        romaji: "Daigakusei desu.",
        vietnamese: "Chị ấy là sinh viên đại học.",
      },
    ],
  },
  {
    id: 502,
    title: "Xem ảnh gia đình",
    category: "Gia đình",
    lines: [
      {
        role: "A",
        japanese: "これは家族の写真ですか？",
        romaji: "Kore wa kazoku no shashin desu ka?",
        vietnamese: "Đây là ảnh gia đình bạn à?",
      },
      {
        role: "B",
        japanese: "はい、そうです。",
        romaji: "Hai, sou desu.",
        vietnamese: "Vâng, đúng vậy.",
      },
      {
        role: "A",
        japanese: "皆さん優しそうですね。",
        romaji: "Minasan yasashisou desu ne.",
        vietnamese: "Mọi người trông hiền hậu nhỉ.",
      },
    ],
  },
  {
    id: 503,
    title: "Sống cùng ai",
    category: "Gia đình",
    lines: [
      {
        role: "A",
        japanese: "一人暮らしですか？",
        romaji: "Hitorigurashi desu ka?",
        vietnamese: "Bạn sống một mình à?",
      },
      {
        role: "B",
        japanese: "いいえ、両親と住んでいます。",
        romaji: "Iie, ryoushin to sundeimasu.",
        vietnamese: "Không, tôi sống cùng bố mẹ.",
      },
    ],
  },
  {
    id: 504,
    title: "Anh chị em",
    category: "Gia đình",
    lines: [
      {
        role: "A",
        japanese: "兄弟はいますか？",
        romaji: "Kyoudai wa imasu ka?",
        vietnamese: "Bạn có anh chị em không?",
      },
      {
        role: "B",
        japanese: "弟が一人います。",
        romaji: "Otouto ga hitori imasu.",
        vietnamese: "Tôi có một em trai.",
      },
    ],
  },
  {
    id: 505,
    title: "Thăm ông bà",
    category: "Gia đình",
    lines: [
      {
        role: "A",
        japanese: "週末は何をしましたか？",
        romaji: "Shuumatsu wa nani wo shimashita ka?",
        vietnamese: "Cuối tuần bạn đã làm gì?",
      },
      {
        role: "B",
        japanese: "祖父母の家に行きました。",
        romaji: "Sofubo no ie ni ikimashita.",
        vietnamese: "Tôi đã đến nhà ông bà.",
      },
    ],
  },

  // --- THỜI TIẾT (WEATHER) ---
  {
    id: 601,
    title: "Hỏi về thời tiết",
    category: "Thời tiết",
    lines: [
      {
        role: "A",
        japanese: "今日の天気はどうですか？",
        romaji: "Kyou no tenki wa dou desu ka?",
        vietnamese: "Thời tiết hôm nay thế nào?",
      },
      {
        role: "B",
        japanese: "雨が降っています。",
        romaji: "Ame ga futteimasu.",
        vietnamese: "Trời đang mưa.",
      },
      {
        role: "A",
        japanese: "寒いですね。",
        romaji: "Samui desu ne.",
        vietnamese: "Lạnh nhỉ.",
      },
      {
        role: "B",
        japanese: "はい、コートを着たほうがいいですよ。",
        romaji: "Hai, kooto wo kita hou ga ii desu yo.",
        vietnamese: "Vâng, bạn nên mặc áo khoác vào.",
      },
    ],
  },
  {
    id: 602,
    title: "Dự báo thời tiết",
    category: "Thời tiết",
    lines: [
      {
        role: "A",
        japanese: "明日の天気予報を見ましたか？",
        romaji: "Ashita no tenki yohou wo mimashita ka?",
        vietnamese: "Bạn đã xem dự báo thời tiết ngày mai chưa?",
      },
      {
        role: "B",
        japanese: "はい、晴れるそうですよ。",
        romaji: "Hai, hareru sou desu yo.",
        vietnamese: "Rồi, nghe nói trời sẽ nắng đấy.",
      },
    ],
  },
  {
    id: 603,
    title: "Mùa yêu thích",
    category: "Thời tiết",
    lines: [
      {
        role: "A",
        japanese: "どの季節が一番好きですか？",
        romaji: "Dono kisetsu ga ichiban suki desu ka?",
        vietnamese: "Bạn thích mùa nào nhất?",
      },
      {
        role: "B",
        japanese: "秋が好きです。涼しいですから。",
        romaji: "Aki ga suki desu. Suzushii desu kara.",
        vietnamese: "Tôi thích mùa thu. Vì trời mát mẻ.",
      },
    ],
  },
  {
    id: 604,
    title: "Trời sắp mưa",
    category: "Thời tiết",
    lines: [
      {
        role: "A",
        japanese: "空が暗いですね。",
        romaji: "Sora ga kurai desu ne.",
        vietnamese: "Trời tối sầm lại nhỉ.",
      },
      {
        role: "B",
        japanese: "雨が降りそうですね。",
        romaji: "Ame ga furisou desu ne.",
        vietnamese: "Có vẻ sắp mưa rồi.",
      },
    ],
  },
  {
    id: 605,
    title: "Tuyết rơi",
    category: "Thời tiết",
    lines: [
      {
        role: "A",
        japanese: "わあ、雪だ！",
        romaji: "Waa, yuki da!",
        vietnamese: "Oa, tuyết kìa!",
      },
      {
        role: "B",
        japanese: "きれいですね。",
        romaji: "Kirei desu ne.",
        vietnamese: "Đẹp quá nhỉ.",
      },
    ],
  },

  // --- CÔNG VIỆC (WORK) ---
  {
    id: 701,
    title: "Hỏi lịch làm việc",
    category: "Công việc",
    lines: [
      {
        role: "A",
        japanese: "明日は仕事をしますか？",
        romaji: "Ashita wa shigoto wo shimasu ka?",
        vietnamese: "Ngày mai bạn có làm việc không?",
      },
      {
        role: "B",
        japanese: "はい、9時から5時までです。",
        romaji: "Hai, kuji kara goji made desu.",
        vietnamese: "Có, từ 9 giờ đến 5 giờ.",
      },
      {
        role: "A",
        japanese: "残業はありますか？",
        romaji: "Zangyou wa arimasu ka?",
        vietnamese: "Có làm thêm giờ không?",
      },
      {
        role: "B",
        japanese: "いいえ、明日はありません。",
        romaji: "Iie, ashita wa arimasen.",
        vietnamese: "Không, mai thì không.",
      },
    ],
  },
  {
    id: 702,
    title: "Phỏng vấn xin việc",
    category: "Công việc",
    lines: [
      {
        role: "A",
        japanese: "自己紹介をお願いします。",
        romaji: "Jikoshoukai wo onegaishimasu.",
        vietnamese: "Mời bạn giới thiệu bản thân.",
      },
      {
        role: "B",
        japanese: "はい、私はグエンと申します。",
        romaji: "Hai, watashi wa Guen to moushimasu.",
        vietnamese: "Vâng, tôi tên là Nguyên.",
      },
    ],
  },
  {
    id: 703,
    title: "Đi công tác",
    category: "Công việc",
    lines: [
      {
        role: "A",
        japanese: "来週、大阪へ出張します。",
        romaji: "Raishuu, Oosaka e shucchou shimasu.",
        vietnamese: "Tuần sau tôi đi công tác Osaka.",
      },
      {
        role: "B",
        japanese: "そうですか。大変ですね。",
        romaji: "Sou desu ka. Taihen desu ne.",
        vietnamese: "Vậy à. Vất vả nhỉ.",
      },
    ],
  },
  {
    id: 704,
    title: "Xin nghỉ phép",
    category: "Công việc",
    lines: [
      {
        role: "A",
        japanese: "すみません、明日休んでもいいですか？",
        romaji: "Sumimasen, ashita yasundemo ii desu ka?",
        vietnamese: "Xin lỗi, ngày mai tôi nghỉ được không?",
      },
      {
        role: "B",
        japanese: "どうしたんですか？",
        romaji: "Doushitan desu ka?",
        vietnamese: "Có chuyện gì vậy?",
      },
      {
        role: "A",
        japanese: "熱があります。",
        romaji: "Netsu ga arimasu.",
        vietnamese: "Tôi bị sốt.",
      },
    ],
  },
  {
    id: 705,
    title: "Ăn trưa cùng đồng nghiệp",
    category: "Công việc",
    lines: [
      {
        role: "A",
        japanese: "一緒に昼ごはんを食べませんか？",
        romaji: "Issho ni hirugohan wo tabemasen ka?",
        vietnamese: "Cùng đi ăn trưa không?",
      },
      {
        role: "B",
        japanese: "いいですね。行きましょう。",
        romaji: "Ii desu ne. Ikimashou.",
        vietnamese: "Hay đấy. Đi thôi.",
      },
    ],
  },
];
